### ISSUE TITLE
Failed to activate the atom-bourbon-snippets package

### ISSUE THREAD

**Issue by robneu** [MarioAraque/atom-bourbon-snippets#1]
First of all, thanks for making this snippet package! I'm getting an error on startup using the latest version of Atom. Here's the automated report it generates:

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-bourbon-snippets](https://github.com/MarioAraque/atom-bourbon-snippets) package, v0.9.0
### Stack Trace

Failed to activate the atom-bourbon-snippets package

```
At Cannot read property 'apply' of undefined

TypeError: Cannot read property 'apply' of undefined
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:122:30)
    at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:96:10)
    at AtomBourbonSnippetsView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:121:33)
    at new AtomBourbonSnippetsView (/Users/robertneu/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:12:60)
    at Object.module.exports.activate (/Users/robertneu/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets.coffee:9:45)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "base16-eighties-one-dark"
    ],
    "disabledPackages": [
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
alignment, v1.1.4
atom-bourbon-snippets, v0.9.0
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
base16-eighties-one-dark, v0.2.1
change-case, v0.5.1
color-picker, v1.4.4
docblockr, v0.6.3
file-icons, v1.5.1
highlight-selected, v0.9.1
linter, v0.12.0
linter-csslint, v0.0.11
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
linter-php, v0.0.11
linter-phpcs, v0.0.12
linter-scss-lint, v0.0.14
project-manager, v1.15.5
sync-settings, v0.2.2
tabs-to-spaces, v0.8.1
trailing-spaces, v0.2.4
wordpress-api, v1.1.0

# Dev
No dev packages
```

**Comment by MarioAraque** [comment]
Hey @robneu 

Thanks for reporting the problem.
It seems to be a problem related with the space-pen dependency. I downgrade the version and upload a new patch and it works.

Could you try to install again the package? Restart Atom and open any .scss file, It should works correctly.

Regards.

**Comment by robneu** [comment]
Yup, looks good now. Thanks!
