### ISSUE TITLE
Failed to load the atom-bourbon-snippets package

### ISSUE THREAD

**Issue by robneu** [MarioAraque/atom-bourbon-snippets#2]
This happens on startup with version 0.1.91.0:

**Atom Version**: 0.191.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-bourbon-snippets](https://github.com/MarioAraque/atom-bourbon-snippets) package, v0.12.5
### Stack Trace

Failed to load the atom-bourbon-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/robertneu/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:4:199)
    at /Users/robertneu/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:9:5
    at Object.<anonymous> (/Users/robertneu/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:39:5)
    at Object.<anonymous> (/Users/robertneu/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:41:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "base16-eighties-one-dark"
    ],
    "disabledPackages": [
      "atom-wordpress-api"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
alignment, v1.1.4
atom-bourbon-snippets, v0.12.5
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
base16-eighties-one-dark, v0.2.1
change-case, v0.5.1
codebug, v0.2.0
color-picker, v1.6.0
docblockr, v0.6.3
file-icons, v1.5.4
highlight-selected, v0.9.1
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-jscs, v1.10.0
linter-jshint, v0.1.2
linter-jsonlint, v0.1.2
linter-php, v0.0.12
linter-phpcs, v0.0.12
linter-scss-lint, v0.0.14
minimap, v4.7.6
project-manager, v1.15.5
status-tab-spacing, v0.3.1
sync-settings, v0.2.2
tabs-to-spaces, v0.9.2
trailing-spaces, v0.2.5
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by MarioAraque** [comment]
It's strange, I've tried to reinstall the package and it works with the 0.192 version.

**Comment by robneu** [comment]
Yeah, same here. I guess it must have been something specific to 0.191
