### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Nick-vr** [MarioAraque/atom-bourbon-snippets#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: elementary OS
**Thrown From**: [atom-bourbon-snippets](https://github.com/MarioAraque/atom-bourbon-snippets) package, v0.14.2
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:4:199)
  at /home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:5:3
  at Object.<anonymous> (/home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:39:5)
  at Object.<anonymous> (/home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets.coffee:1:27)
  at Object.<anonymous> (/home/robin/.atom/packages/atom-bourbon-snippets/lib/atom-bourbon-snippets.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/opt/atom/resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /opt/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/opt/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -3:49.6.0 core:redo (atom-text-editor.editor.is-focused)
     -3:48.6.0 core:undo (atom-text-editor.editor.is-focused)
  2x -3:47.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:24.2.0 core:cut (atom-text-editor.editor.is-focused)
     -3:20.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:20.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:20.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:20.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:20.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:20 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:20 editor:newline (atom-text-editor.editor.is-focused)
     -3:19.8.0 core:paste (atom-text-editor.editor.is-focused)
  5x -1:41.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:38.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "redui-jm-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.5
autoclose-html, v0.18.0
color-picker, v2.0.4
css-snippets, v0.8.0
emmet, v2.3.10
file-icons, v1.5.7
foundation5-snippets, v0.2.1
javascript-snippets, v1.0.0
linter, v0.12.7
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
linter-php, v0.0.15
linter-scss-lint, v1.0.4
meteor-api, v2.19.0
pigments, v0.7.2
project-manager, v1.15.10
redui-jm-syntax, v0.5.1

# Dev
No dev packages
```

**Comment by MarioAraque** [comment]
I've updated the plugin and it works well.

If the problem persist, feel free to open a new issue.
